server:
  port: 8082

spring:
  application:
   name: RepairService
  datasource:
    url: ${RDB}
    username: ${RU}
    password: ${RP}
  jpa:
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    drop-first: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
    instances:
      PersonalService:
        base-config: default
        failureRateThreshold: 50
        waitDurationInOpenState: 10s






