server:
  port: 8081

spring:
  application:
    name: PersonalService
  datasource:
    url: ${PDB}
    username: ${PU}
    password: ${PP}
  jpa:
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    drop-first: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
