server:
  port: 8081

spring:
  application:
    name: PersonalService
  datasource:
    url: ${PDB}
    username: ${PU}
    password: ${PP}
  jpa:
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    drop-first: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: a-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG # Логирование SQL-запросов
        type:
          descriptor:
            sql:
              BasicBinder: TRACE # Логирование параметров SQL-запросов
    root: INFO
  loggers:
    hibernate:
      SQL: DEBUG # Логирование SQL-запросов
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE # Логирование параметров запросов